//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskMasterMobilePolivanov.DataBaseF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Session1_TaskMaster_PolivanovEntities : DbContext
    {
        public Session1_TaskMaster_PolivanovEntities()
            : base("name=Session1_TaskMaster_PolivanovEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Analizator> Analizator { get; set; }
        public virtual DbSet<InsuranceCompany> InsuranceCompany { get; set; }
        public virtual DbSet<InsurancePoliceType> InsurancePoliceType { get; set; }
        public virtual DbSet<InsurancePolicy> InsurancePolicy { get; set; }
        public virtual DbSet<Invoicing> Invoicing { get; set; }
        public virtual DbSet<LabServices> LabServices { get; set; }
        public virtual DbSet<OrderComplate> OrderComplate { get; set; }
        public virtual DbSet<OrderInfo> OrderInfo { get; set; }
        public virtual DbSet<Pacient> Pacient { get; set; }
        public virtual DbSet<PacientLabService> PacientLabService { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserLab> UserLab { get; set; }
        public virtual DbSet<UserLabServices> UserLabServices { get; set; }
    }
}
