//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskMasterMobilePolivanov.DataBaseF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoicing
    {
        public int Id { get; set; }
        public Nullable<int> IdInsuranceCompany { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> IdOrderComplate { get; set; }
    
        public virtual InsuranceCompany InsuranceCompany { get; set; }
        public virtual OrderComplate OrderComplate { get; set; }
        public virtual UserLab UserLab { get; set; }
    }
}
