//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskMasterMobilePolivanov.DataBaseF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderComplate
    {
        public int Id { get; set; }
        public Nullable<int> IdOreder { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<System.DateTime> DateComplate { get; set; }
        public Nullable<int> IdAnalizator { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public Nullable<bool> Accepted { get; set; }
        public Nullable<decimal> Result { get; set; }
    
        public virtual Analizator Analizator { get; set; }
        public virtual OrderInfo OrderInfo { get; set; }
        public virtual Status Status { get; set; }
        public virtual UserLab UserLab { get; set; }
    }
}
