//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskMasterMobilePolivanov.DataBaseF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PacientLabService
    {
        public int Id { get; set; }
        public Nullable<int> IdLabServices { get; set; }
        public Nullable<int> IdPacient { get; set; }
    
        public virtual LabServices LabServices { get; set; }
        public virtual Pacient Pacient { get; set; }
    }
}
